# Generated by Django 3.1.7 on 2023-10-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20231012_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='countProduct',
            field=models.IntegerField(default=0),
        ),
    ]
